import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "./components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-blue-950`}>
        {/* <Image
          width={2200}
          height={1000}
          alt="landing"
          src={bg}
          className="w-screen object-cover fixed -z-10 h-screen"
        ></Image> */}
        {children}
      </body>
    </html>
  );
}
